INSERT IGNORE INTO cap_product (productname, category, proddescription, image, price)
VALUES 
    ('Guitar', 'Instruments', 'Is an instrument with strings that makes music',
				'img/basic_guitar.jpg', 100),
    ('Expensive Guitar', 'Instruments', 'Is an instrument with strings that makes music',
				'img/expensive_guitar.jpg', 500),
    ('Trombone', 'Instruments', 'Takes in air to make music',
				'img/basic_trombone.jpg', 500),
    ('Expensive Trombone', 'Instruments', 'Takes in air to make music',
				'img/expensive_trombone.jpg', 1900),
    ('Eukalele', 'Instruments', 'Is an instrument with strings that makes music',
				'img/eukalele.jpg', 100),
    ('Violin', 'Instruments', 'Is an instrument with strings and a stick that makes music',
				'img/violin.jpg', 600),
    ('Drums', 'Instruments', 'Beat it till you make it',
				'img/drum_set.jpg', 1200),
    ('Marshall Mathers LP 1', 'Music', 'Album by Eminem',
				'img/mmlp.jpg', 10),
    ('Straight Outta Compton', 'Music', 'Album by N.W.A.',
				'img/soc.jpg', 10),
    ('Sigh No More', 'Music', 'Album by Mumford & Sons',
				'img/snm.jpg', 10),
    ('Into the woods', 'Music', 'Album by Of Monsters and Men',
				'img/itw.jpg', 10);